name: Package
on:
  push:
    branches:
      - dev
jobs:
  publish:
    name: Publish to NuGet.org
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-version: '6.x'

      - name: Create the package
        run: nuget restore Blazor.Serilog.Sinks.SQLite.sln
        
     
