name: Package
on:
  push:
    branches:
      - dev
jobs:
  publish:
    name: Publish to NuGet.org
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore


      - name: Pack
        run: dotnet pack --configuration Release -o out

      - name: Publish to NuGet
        run: dotnet nuget push "out/*.nupkg" --source https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
    
